# Site settings
theme: minima
title: Heimdall Documentation
description: A Secure, Verifiable IAM for AI Agents
baseurl: "/Docs"
url: "https://iam-heimdall.github.io"

# Author/Organization info (appears in footer)
author:
  name: Heimdall
  email: # optional
  
# Social links (appear in footer and header)
minima:
  social_links:
    - { platform: website, user_url: "https://iamheimdall.com" }

# Navigation header (just essential links)
header_pages:
  - index.md

# Footer
footer: "All rights reserved. 2025"

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md