# Site settings
theme: minima
title: Heimdall Documentation
description: A Secure, Verifiable IAM for AI Agents
baseurl: "/Docs"
url: "https://iam-heimdall.github.io"

# Author/Organization info (appears in footer)
author:
  name: Heimdall Team
  
# Logo settings
logo: /images/logo.png

# Social links (appear in footer)
minima:
  social_links:
    - { platform: website, user_url: "https://iamheimdall.com" }

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md