# Site settings
theme: minima
title: Heimdall Summary
description: A Secure, Verifiable IAM for AI Agents
baseurl: ""
url: "https://docs.iamheimdall.com"

  
# Social links (appear in footer and header)
minima:
  social_links:
    - { platform: website, user_url: "https://iamheimdall.com" }

# Navigation header (just essential links)
header_pages:
  - index.md

# Footer
footer: "All rights reserved. 2025"

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
